routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BillController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SusterController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('/admin')->group(function (){
    Route::resource('/doctor', DoctorController::class);
    Route::resource('/suster', SusterController::class);
    Route::resource('/room', RoomController::class);
});
Route::prefix('/receptionist')->group(function (){
    Route::resource('/patient', PatientController::class);
    Route::resource('/pendaftaran', PendaftaranController::class);
    Route::resource('/obat', ObatController::class);
});


Route::get('/admin', [AdminController::class, 'admin'])->name('admin');
Route::put('/{admin}', [AdminController::class, 'update'])->name('admin.update');

Route::get('/profile', [ClientController::class, 'profile'])->name('profile');
Route::put('/{profile}', [ClientController::class, 'updateRecep'])->name('profile.update.recep');


Route::resource('/bill', BillController::class);

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;
    public function levels(){
        return $this->belongsTo(Level::class, 'level_id');
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Models\Level;
use App\Models\Room;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $levels = Level::orderBy('created_at', 'desc')->get();
        $rooms = Room::orderBy('created_at', 'desc')->get();
        return view('admin.rooms.index',compact('rooms','levels'));
    }

    public function create()
    {
        $levels = Level::orderBy('created_at', 'desc')->get();
        return view('admin.rooms.create', compact('levels'));
    }

    public function store(Request $request)
    {
        $room = new Room();
        $room->nameRoom = $request->nameRoom;
        $room->priceRoom = $request->priceRoom;
        $room->level_id = $request->level_id;
        $room->save();
        return redirect(route('room.index'));

    }
    public function edit($id)
    {
        $rooms = Room::where('id', $id)->first();
        $levels = Level::orderBy('created_at', 'desc')->get();
        return view('admin.rooms.edit', compact('rooms','levels'));
    }

    public function update(Request $request, $id)
    {
        $room = Room::find($id);
        $room->nameRoom = $request->nameRoom;
        $room->priceRoom = $request->priceRoom;
        $room->level_id = $request->level_id;
        $room->update();
        return redirect(route('room.index'));

    }
    public function destroy($id)
    {
        $room = Room::find($id);
        $room->delete();
        return redirect(route('room.index'));
    }
}

resources/views/admin/rooms/create.blade.php
@extends('layouts.master')
@section('title')
    Doctor
@endsection
@section('content')
    <div class="page-wrapper full-calender">
        <div class="page-body">
            <div class="row">


                <div class="row col-lg-12">
                    <h3><b>Add Doctor</b></h3>
                </div>
                <div class="row col-lg-12">Welcome to Abuya Kangean Hospital<br><br></div>

                <div class="card row col-lg-12">
                    <div class="card-block">
                        <!-- Row start -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content card-block">
                                    <div class="tab-pane active" id="home3" role="tabpanel">
                                        <form method="post" action="{{ route('room.store') }}">
                                            @csrf
                                            <p style="font-size:16px; color:red" align="center">
                                            <div class="form-group"> <label for="exampleInputEmail1">Room Name</label>
                                                <input type="text" class="form-control" id="nameRoom" name="nameRoom"
                                                    placeholder="Room Name" value="" required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputPassword1">Room Price</label>
                                                <input type="number" id="cost" name="priceRoom" class="form-control"
                                                    placeholder="Room Price" value="" required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputPassword1">Level Room</label>
                                                <select name="level_id" id="level_id" required="true" class="form-control">
                                                    <option value="">Pilih Level Room</option>
                                                    @foreach ($levels as $lv)
                                                        <option value="{{ $lv->id }}">
                                                            {{ $lv->nameLevel }}
                                                    @endforeach
                                                    </option>

                                                </select>
                                            </div>

                                            <button type="submit" name="submit" class="btn btn-default">Add</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Row end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/rooms/edit.blade.php
@extends('layouts.master')
@section('title')
    Room
@endsection
@section('content')
    <div class="page-wrapper full-calender">
        <div class="page-body">
            <div class="row">


                <div class="row col-lg-12">
                    <h3><b>Edit Room</b></h3>
                </div>
                <div class="row col-lg-12">Profil of Doctor : {{ $rooms->name }}<br><br></div>

                <div class="card row col-lg-12">
                    <div class="card-block">
                        <!-- Row start -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content card-block">
                                    <div class="tab-pane active" id="home3" role="tabpanel">
                                        <form method="post" action="{{ route('room.update', $rooms->id) }}">
                                            @csrf
                                            @method('PUT')
                                            <p style="font-size:16px; color:red" align="center">
                                            <div class="form-group"> <label for="exampleInputEmail1">Room Name</label>
                                                <input type="text" class="form-control" id="nameRoom" name="nameRoom"
                                                    placeholder="Room Name" value="{{ $rooms->nameRoom }}"
                                                    required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputPassword1">Room Price</label>
                                                <input type="number" id="cost" name="priceRoom" class="form-control"
                                                    placeholder="Room Price" value="{{ $rooms->priceRoom }}"
                                                    required="true">
                                            </div>
                                            @foreach ($levels as $lv)
                                                @if ($rooms->level_id != null && $rooms->level_id == $lv->id)
                                                    <label class="bmd-label-floating">Level Ruangan | Selected Id
                                                        ({{ $lv->nameLevel }})</label>
                                                @else

                                                @endif
                                            @endforeach
                                            <div class="form-group">
                                                <select name="level_id" id="level_id" required="true" class="form-control">
                                                    <option value="">Pilih Level Room</option>
                                                    @foreach ($levels as $lv)
                                                        <option value="{{ $lv->id }}">
                                                            {{ $lv->nameLevel }}
                                                    @endforeach
                                                    </option>

                                                </select>
                                            </div>

                                            <button type="submit" name="submit" class="btn btn-default">Update</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Row end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/rooms/index.blade.php
@extends('layouts.master')
@section('title')
    Doctors
@endsection
@section('content')
    <div class="card">
        <div class="card-header">
            <h2>Data Doctors</h2>

        </div>
        <div class="card-block">
            <div class="table-responsive dt-responsive">
                <table id="example1" class="table table-striped table-bordered nowrap">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Room Name</th>
                            <th>Room Price</th>
                            <th>Room Level</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($rooms as $key => $room)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td> {{ $room->nameRoom }} </td>
                                <td> {{ $room->priceRoom }} </td>

                                <td>
                                    @foreach ($levels as $lv)
                                        @if ($lv->id == $room->level_id)
                                            {{ $lv->nameLevel }}
                                        @endif
                                    @endforeach
                                </td>
                                <td>
                                    <a href="{{ route('room.edit', ['room' => $room]) }}" class="btn btn-info"><i
                                            class="fa fa-pencil"></i> Edit </a>

                                    <form action="{{ route('room.destroy', ['room' => $room]) }}" style="display: inline;"
                                        method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger text-light">
                                            <i class="fa fa-trash" aria-hidden="true">
                                                Delete
                                            </i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });

    </script>
@endpush