routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BillController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SusterController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('/admin')->group(function (){
    Route::resource('/doctor', DoctorController::class);
    Route::resource('/suster', SusterController::class);
    Route::resource('/room', RoomController::class);
});
Route::prefix('/receptionist')->group(function (){
    Route::resource('/patient', PatientController::class);
    Route::resource('/pendaftaran', PendaftaranController::class);
    Route::resource('/obat', ObatController::class);
});


Route::get('/admin', [AdminController::class, 'admin'])->name('admin');
Route::put('/{admin}', [AdminController::class, 'update'])->name('admin.update');

Route::get('/profile', [ClientController::class, 'profile'])->name('profile');
Route::put('/{profile}', [ClientController::class, 'updateRecep'])->name('profile.update.recep');


Route::resource('/bill', BillController::class);

app/Http/Controllers/PendaftaranController.php
<?php

namespace App\Http\Controllers;

use App\Models\Booking;
use App\Models\Doctor;
use App\Models\Obat;
use App\Models\Patient;
use App\Models\Suster;
use Illuminate\Http\Request;

class PendaftaranController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pendaftaran = Booking::orderBy('created_at', 'desc')->get();
        return view('receptionist.pendaftaran.index', compact('pendaftaran'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $patient = Patient::orderBy('created_at', 'desc')->get();
        $suster = Suster::orderBy('created_at', 'desc')->get();
        $doctor = Doctor::orderBy('created_at', 'desc')->get();
        $obat = Obat::orderBy('created_at', 'desc')->get();
        return view('receptionist.pendaftaran.create',compact('patient','suster','doctor','obat'));
    }

    public function store(Request $request)
    {
        $pendaftaran = new Booking;
        $pendaftaran->patient_id = $request->patient_id;
        $pendaftaran->suster_id = $request->suster_id;
        $pendaftaran->doctor_id = $request->doctor_id;
        $pendaftaran->obat_id = $request->doctor_id;
        $pendaftaran->save();
        return redirect(route('pendaftaran.index'));
    }

    public function edit($id)
    {
        $patient = Patient::orderBy('created_at', 'desc')->get();
        $suster = Suster::orderBy('created_at', 'desc')->get();
        $doctor = Doctor::orderBy('created_at', 'desc')->get();
        $pendaftaran = Booking::where('id', $id)->first();
        $obat = Obat::orderBy('created_at', 'desc')->get();
        return view('receptionist.pendaftaran.edit', compact('pendaftaran','patient','suster','doctor','obat'));
    }
    public function update(Request $request, $id)
    {
        $pendaftaran = Booking::find($id);
        $pendaftaran->patient_id = $request->patient_id;
        $pendaftaran->suster_id = $request->suster_id;
        $pendaftaran->doctor_id = $request->doctor_id;
        $pendaftaran->obat_id = $request->doctor_id;
        $pendaftaran->update();
        return redirect(route('pendaftaran.index'));
    }
    public function destroy($id)
    {
        $pendaftaran = Booking::find($id);
        $pendaftaran->delete();
        return redirect(route('pendaftaran.index'));
    }
}

resources/views/receptionist/pendaftaran/create.blade.php
@extends('layouts.master')
@section('title')
    Pendaftaran
@endsection
@section('content')
    <div class="page-wrapper full-calender">
        <div class="page-body">
            <div class="row">


                <div class="row col-lg-12">
                    <h3><b>Add Pendaftaran</b></h3>
                </div>
                <div class="row col-lg-12">Welcome to Abuya Kangean Hospital<br><br></div>

                <div class="card row col-lg-12">
                    <div class="card-block">
                        <!-- Row start -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content card-block">
                                    <div class="tab-pane active" id="home3" role="tabpanel">
                                        <form action="{{ route('pendaftaran.store') }}" method="POST"
                                            data-parsley-validate class="appointment-form">
                                            @csrf
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <select name="patient_id" id="patient_id" required="true"
                                                            class="form-control">
                                                            <option value="">Pilih Pasien</option>
                                                            @foreach ($patient as $p)
                                                                <option value="{{ $p->id }}">
                                                                    {{ $p->name }} - {{ $p->email }}
                                                            @endforeach
                                                            </option>

                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <div class="select-wrap">
                                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                                            <select name="suster_id" id="suster_id" required="true"
                                                                class="form-control">
                                                                <option value="">Pilih Suster</option>
                                                                @foreach ($suster as $s)
                                                                    <option value="{{ $s->id }}">
                                                                        {{ $s->name }}
                                                                @endforeach
                                                                </option>

                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <div class="select-wrap">
                                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                                            <select name="doctor_id" id="doctor_id" required="true"
                                                                class="form-control">
                                                                <option value="">Pilih Doktor</option>
                                                                @foreach ($doctor as $d)
                                                                    <option value="{{ $d->id }}">
                                                                        {{ $d->name }}
                                                                @endforeach
                                                                </option>

                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <div class="select-wrap">
                                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                                            <select name="doctor_id" id="doctor_id" required="true"
                                                                class="form-control">
                                                                <option value="">Pilih Obat</option>
                                                                @foreach ($obat as $o)
                                                                    <option value="{{ $o->id }}">
                                                                        {{ $o->obatName }}
                                                                @endforeach
                                                                </option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" name="submit" value="Buat Pemesanan"
                                                    class="btn btn-primary">
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Row end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/receptionist/pendaftaran/edit.blade.php
@extends('layouts.master')
@section('title')
    Pendaftaran
@endsection
@section('content')
    <div class="page-wrapper full-calender">
        <div class="page-body">
            <div class="row">


                <div class="row col-lg-12">
                    <h3><b>Edit Pendaftaran</b></h3>
                </div>
                <div class="row col-lg-12">Welcome to Abuya Kangean Hospital<br><br></div>

                <div class="card row col-lg-12">
                    <div class="card-block">
                        <!-- Row start -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content card-block">
                                    <div class="tab-pane active" id="home3" role="tabpanel">
                                        <form action="{{ route('pendaftaran.update', $pendaftaran->id) }}" method="POST"
                                            data-parsley-validate class="appointment-form">
                                            @csrf
                                            @method('PUT')
                                            <div class="row">
                                                @if ($pendaftaran->patients->name != null)
                                                    <label class="bmd-label-floating">Nama Pasien | Selected
                                                        ({{ $pendaftaran->patients->name }})</label>
                                                @else
                                                    <label class="bmd-label-floating">Nama Pasien | Not Yet
                                                        Selected</label>
                                                @endif
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <select name="patient_id" id="patient_id" required="true"
                                                            class="form-control">
                                                            <option value="">Pilih Pasien</option>
                                                            @foreach ($patient as $p)
                                                                <option value="{{ $p->id }}">
                                                                    {{ $p->name }} - {{ $p->email }}
                                                            @endforeach
                                                            </option>

                                                        </select>
                                                    </div>
                                                </div>
                                                @if ($pendaftaran->susters->name != null)
                                                    <label class="bmd-label-floating">Nama Suster | Selected
                                                        ({{ $pendaftaran->susters->name }})</label>
                                                @else
                                                    <label class="bmd-label-floating">Nama Suster | Not Yet
                                                        Selected</label>
                                                @endif
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <div class="select-wrap">
                                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                                            <select name="suster_id" id="suster_id" required="true"
                                                                class="form-control">
                                                                <option value="">Pilih Suster</option>
                                                                @foreach ($suster as $s)
                                                                    <option value="{{ $s->id }}">
                                                                        {{ $s->name }}
                                                                @endforeach
                                                                </option>

                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                @if ($pendaftaran->doctors->name != null)
                                                    <label class="bmd-label-floating">Nama Dokter | Selected
                                                        ({{ $pendaftaran->doctors->name }})</label>
                                                @else
                                                    <label class="bmd-label-floating">Nama Dokter | Not Yet
                                                        Selected</label>
                                                @endif
                                                <div class="col-sm-12">
                                                    <div class="form-group">
                                                        <div class="select-wrap">
                                                            <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                                            <select name="doctor_id" id="doctor_id" required="true"
                                                                class="form-control">
                                                                <option value="">Pilih Doktor</option>
                                                                @foreach ($doctor as $d)
                                                                    <option value="{{ $d->id }}">
                                                                        {{ $d->name }}
                                                                @endforeach
                                                                </option>

                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" name="submit" value="Buat pendaftaran"
                                                    class="btn btn-primary">
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Row end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/receptionist/pendaftaran/index.blade.php
@extends('layouts.master')
@section('title')
    Pendaftaran
@endsection
@section('content')
    <div class="card">
        <div class="card-header">
            <h2>List Pendaftaran</h2>

        </div>
        <div class="card-block">
            <div class="table-responsive dt-responsive">
                <table id="example1" class="table table-striped table-bordered nowrap">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Ruangan</th>
                            <th>Nama Pasien</th>
                            <th>Nama Perawat</th>
                            <th>Nama Doktor</th>
                            <th>Waktu Masuk</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($pendaftaran as $key => $pendaftaran)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td>{{ $pendaftaran->susters->rooms->nameRoom }} -
                                    {{ $pendaftaran->susters->rooms->levels->nameLevel }} </td>
                                <td> {{ $pendaftaran->patients->name }} </td>
                                <td> {{ $pendaftaran->doctors->name }} </td>
                                <td> {{ $pendaftaran->susters->name }} </td>
                                <td> {{ $pendaftaran->created_at }} </td>
                                <td>
                                    <a href="{{ route('pendaftaran.edit', ['pendaftaran' => $pendaftaran]) }}"
                                        class="btn btn-info"><i class="fa fa-pencil"></i> Edit </a>

                                    <form action="{{ route('pendaftaran.destroy', ['pendaftaran' => $pendaftaran]) }}"
                                        style="display: inline;" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger text-light">
                                            <i class="fa fa-trash" aria-hidden="true">
                                                Delete
                                            </i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });

    </script>
@endpush