routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BillController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SusterController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('/admin')->group(function (){
    Route::resource('/doctor', DoctorController::class);
    Route::resource('/suster', SusterController::class);
    Route::resource('/room', RoomController::class);
});
Route::prefix('/receptionist')->group(function (){
    Route::resource('/patient', PatientController::class);
    Route::resource('/pendaftaran', PendaftaranController::class);
    Route::resource('/obat', ObatController::class);
});


Route::get('/admin', [AdminController::class, 'admin'])->name('admin');
Route::put('/{admin}', [AdminController::class, 'update'])->name('admin.update');

Route::get('/profile', [ClientController::class, 'profile'])->name('profile');
Route::put('/{profile}', [ClientController::class, 'updateRecep'])->name('profile.update.recep');


Route::resource('/bill', BillController::class);

resources/views/layouts/modules/footer.blade.php
<footer class="footer text-center">
    <marquee behavior="alternate">© 2021 All Rights are Reserved <a href="nikhilbhalerao.com" target="_blank"
            style="color: yellow;">Developed by Halimatus Sakdiyah</a></marquee>
</footer>

resources/views/layouts/modules/navbar.blade.php
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">
        <div class="navbar-logo">

            <a href="dashboard.php">

                <div class="text-center">
                    <img class="profile-img" src="{{ asset('uploadImage/Logo/logo-for-hospital-system.jpg') }}"
                        style="width: 50%">
                </div>
            </a>
            <a class="mobile-options">
                <i class="feather icon-more-horizontal"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <ul class="nav-left">
                <li>
                    <a href="#!" onclick="javascript:toggleFullScreen()">
                        <i class="feather icon-maximize full-screen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                <li class="user-profile header-notification">
                    <div class="dropdown-primary dropdown">
                        <div class="dropdown-toggle" data-toggle="dropdown">
                            @if (Auth::user()->avatar != null)
                                <img class="profile-img" src="{{ asset('profile/' . Auth::user()->avatar) }}"
                                    style="width: 40px; border-radius:50%;">
                            @else
                                <img class="profile-img" src="{{ asset('uploadImage/Profile/profile.jpg') }}"
                                    style="width: 40px; border-radius:50%;">
                            @endif
                            <span></span>
                            <i class="feather icon-chevron-down"></i>
                        </div>
                        <ul class="show-notification profile-notification dropdown-menu" data-dropdown-in="fadeIn"
                            data-dropdown-out="fadeOut">

                            <li>
                                @if (Auth::user()->is_admin == 1)
                                    <a href="{{ route('admin.home') }}">
                                        <i class="feather icon-user"></i> Profile
                                    </a>
                                @else
                                    <a href="{{ route('home') }}">
                                        <i class="feather icon-user"></i> Profile
                                    </a>
                                @endif

                            </li>

                            <li>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                    <i class="feather icon-log-out"></i> Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/modules/sidebar.blade.php
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel">{{ Auth::user()->username }}</div>
        <ul class="pcoded-item pcoded-left-item">
            @if (Auth::user()->is_admin == 1)
                <li class="">
                    <a href="{{ route('admin.home') }}">
                        <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                        <span class="pcoded-mtext">Dashboard</span>
                    </a>
                </li>

                <li class="pcoded-hasmenu">
                    <a href="javascript:void(0)">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                        <span class="pcoded-mtext">Doctor</span>
                    </a>
                    <ul class="pcoded-submenu">

                        <li class="">
                            <a href="{{ route('doctor.create') }}">
                                <span class="pcoded-mtext">New Doctor</span>
                            </a>
                        </li>

                        <li class="">
                            <a href="{{ route('doctor.index') }}">
                                <span class="pcoded-mtext">View Doctor</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:void(0)">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                        <span class="pcoded-mtext">Suster</span>
                    </a>
                    <ul class="pcoded-submenu">

                        <li class="">
                            <a href="{{ route('suster.create') }}">
                                <span class="pcoded-mtext">New Suster</span>
                            </a>
                        </li>

                        <li class="">
                            <a href="{{ route('suster.index') }}">
                                <span class="pcoded-mtext">View Suster</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:void(0)">
                        <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                        <span class="pcoded-mtext">Room</span>
                    </a>
                    <ul class="pcoded-submenu">

                        <li class="">
                            <a href="{{ route('room.create') }}">
                                <span class="pcoded-mtext">New Room</span>
                            </a>
                        </li>

                        <li class="">
                            <a href="{{ route('room.index') }}">
                                <span class="pcoded-mtext">View Room</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:void(0)">
                        <span class="pcoded-micon"><i class="feather icon-menu"></i></span>
                        <span class="pcoded-mtext">Obat</span>
                    </a>
                    <ul class="pcoded-submenu">

                        <li class="">
                            <a href="{{ route('obat.create') }}">
                                <span class="pcoded-mtext">Add Obat</span>
                            </a>
                        </li>

                        <li class="">
                            <a href="{{ route('obat.index') }}">
                                <span class="pcoded-mtext">List Obat</span>
                            </a>
                        </li>
                    </ul>
                </li>

            @else
                <li class="">
                    <a href="{{ route('home') }}">
                        <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                        <span class="pcoded-mtext">Dashboard</span>
                    </a>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:void(0)">
                        <span class="pcoded-micon"><i class="feather icon-edit"></i></span>
                        <span class="pcoded-mtext">Pendaftaran</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li class="">
                            <a href="{{ route('pendaftaran.create') }}">
                                <span class="pcoded-mtext">Pendaftaran Baru</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="{{ route('pendaftaran.index') }}">
                                <span class="pcoded-mtext">List Pendaftaran</span>
                            </a>
                        </li>

                    </ul>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:void(0)">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                        <span class="pcoded-mtext">Patient</span>
                    </a>
                    <ul class="pcoded-submenu">

                        <li class="">
                            <a href="{{ route('patient.create') }}">
                                <span class="pcoded-mtext">Tambah Data Pasien</span>
                            </a>
                        </li>

                        <li class="">
                            <a href="{{ route('patient.index') }}">
                                <span class="pcoded-mtext">List Pasien</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="pcoded-submenu">
                    <a href="{{ route('bill.index') }}">
                        <span class="pcoded-micon"><i class="feather icon-file"></i></span>
                        <span class="pcoded-mtext">Pembayaran</span>
                    </a>
                </li>
            @endif
        </ul>
    </div>
</nav>