routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BillController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\SusterController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('/admin')->group(function (){
    Route::resource('/doctor', DoctorController::class);
    Route::resource('/suster', SusterController::class);
    Route::resource('/room', RoomController::class);
});
Route::prefix('/receptionist')->group(function (){
    Route::resource('/patient', PatientController::class);
    Route::resource('/pendaftaran', PendaftaranController::class);
    Route::resource('/obat', ObatController::class);
});


Route::get('/admin', [AdminController::class, 'admin'])->name('admin');
Route::put('/{admin}', [AdminController::class, 'update'])->name('admin.update');

Route::get('/profile', [ClientController::class, 'profile'])->name('profile');
Route::put('/{profile}', [ClientController::class, 'updateRecep'])->name('profile.update.recep');


Route::resource('/bill', BillController::class);

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    use HasFactory;
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Patient;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $patient = Patient::orderBy('created_at', 'desc')->get();
        return view('receptionist.patient.index',compact('patient'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('receptionist.patient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // dd($request);
        $patient = new patient;
        $patient->name = $request->name;
        $patient->email = $request->email;
        $patient->tlp = $request->tlp;
        $patient->jeniskelamin = $request->jeniskelamin;
        $patient->detail = $request->details;

        $patient->save();
        return redirect(route('patient.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $patient = patient::where('id', $id)->first();
        return view('receptionist.patient.edit', compact('patient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $patient = Patient::find($id);
        $patient->name = $request->name;
        $patient->email = $request->email;
        $patient->tlp = $request->tlp;
        $patient->jeniskelamin = $request->jeniskelamin;
        $patient->detail = $request->details;

        $patient->update();
        return redirect(route('patient.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $patient = Patient::find($id);
        $patient->delete();
        return redirect(route('patient.index'));
    }
}

resources/views/receptionist/patient/create.blade.php
@extends('layouts.master')
@section('title')
    Pasien
@endsection
@section('content')
    <div class="page-wrapper full-calender">
        <div class="page-body">
            <div class="row">


                <div class="row col-lg-12">
                    <h3><b>Add Pasien</b></h3>
                </div>
                <div class="row col-lg-12">Welcome to Abuya Kangean Hospital<br><br></div>

                <div class="card row col-lg-12">
                    <div class="card-block">
                        <!-- Row start -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content card-block">
                                    <div class="tab-pane active" id="home3" role="tabpanel">
                                        <form action="{{ route('patient.store') }}" method="POST" data-parsley-validate
                                            enctype="multipart/form-data">
                                            @csrf

                                            <div class="form-group"> <label for="exampleInputEmail1">Name</label> <input
                                                    type="text" class="form-control" id="name" name="name"
                                                    placeholder="Full Name" value="" required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputEmail1">Email</label> <input
                                                    type="email" class="form-control" id="email" name="email"
                                                    placeholder="Email" value="" required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputEmail1">Mobile Number</label>
                                                <input type="number" class="form-control" id="mobilenum" name="tlp"
                                                    placeholder="Mobile Number" value="" required="true" maxlength="10"
                                                    pattern="[0-9]+"> </div>
                                            <div class="radio">

                                                <p style="padding-top: 20px; font-size: 15px"> <strong>Gender:</strong>
                                                    <label>
                                                        <input type="radio" name="jeniskelamin" id="gender"
                                                            value="Perempuan" checked="true">
                                                        Perempuan
                                                    </label>
                                                    <label>
                                                        <input type="radio" name="jeniskelamin" id="gender"
                                                            value="Laki-laki">
                                                        Laki-laki
                                                    </label>
                                                </p>
                                            </div>
                                            <div class="form-group"> <label for="exampleInputEmail1">Details</label>
                                                <textarea type="text" class="form-control" id="details" name="details"
                                                    placeholder="Details" required="true" rows="12" cols="4"></textarea>
                                            </div>
                                            <br>
                                            <button type="submit" name="submit" class="btn btn-default">Add</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Row end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/receptionist/patient/edit.blade.php
@extends('layouts.master')
@section('title')
    Pasien
@endsection
@section('content')
    <div class="page-wrapper full-calender">
        <div class="page-body">
            <div class="row">


                <div class="row col-lg-12">
                    <h3><b>Add Pasien</b></h3>
                </div>
                <div class="row col-lg-12">Welcome to Abuya Kangean Hospital<br><br></div>

                <div class="card row col-lg-12">
                    <div class="card-block">
                        <!-- Row start -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="tab-content card-block">
                                    <div class="tab-pane active" id="home3" role="tabpanel">
                                        <form action="{{ route('patient.update', $patient->id) }}" method="POST"
                                            data-parsley-validate enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                            <div class="form-group"> <label for="exampleInputEmail1">Name</label> <input
                                                    type="text" class="form-control" id="name" name="name"
                                                    placeholder="Full Name" value="{{ $patient->name }}" required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputEmail1">Email</label> <input
                                                    type="email" class="form-control" id="email" name="email"
                                                    placeholder="Email" value="{{ $patient->email }}" required="true">
                                            </div>
                                            <div class="form-group"> <label for="exampleInputEmail1">Mobile Number</label>
                                                <input type="" class="form-control" id="mobilenum" name="tlp"
                                                    placeholder="Mobile Number" value="{{ $patient->tlp }}"
                                                    required="true">
                                            </div>
                                            <div class="radio">

                                                <p style="padding-top: 20px; font-size: 15px"> <strong>Gender:</strong>
                                                    <label>
                                                        <input type="radio" name="jeniskelamin" id="gender"
                                                            value="Perempuan" checked="true">
                                                        Perempuan
                                                    </label>
                                                    <label>
                                                        <input type="radio" name="jeniskelamin" id="gender"
                                                            value="Laki-laki">
                                                        Laki-laki
                                                    </label>
                                                </p>
                                                @if ($patient->jeniskelamin != null)
                                                    <label class="bmd-label-floating">Jenis Kelamin | Choosed
                                                        ({{ $patient->jeniskelamin }})</label>
                                                @else
                                                    <label class="bmd-label-floating">Jenis Kelamin | Not Yet
                                                        Choosed</label>
                                                @endif
                                            </div>
                                            <div class="form-group"> <label for="exampleInputEmail1">Details</label>
                                                <textarea type="text" class="form-control" id="details" name="details"
                                                    placeholder="Details" required="true" rows="12"
                                                    cols="4">{{ $patient->detail }}</textarea>
                                            </div>
                                            <br>
                                            <button type="submit" name="submit" class="btn btn-default">Update</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Row end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/receptionist/patient/index.blade.php
@extends('layouts.master')
@section('title')
    Pasien
@endsection
@section('content')
    <div class="card">
        <div class="card-header">
            <h2>Data Pasien</h2>

        </div>
        <div class="card-block">
            <div class="table-responsive dt-responsive">
                <table id="example1" class="table table-striped table-bordered nowrap">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>patient Name</th>
                            <th>Email</th>
                            <th>No. Telp</th>
                            <th>Jenis Kelamin</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($patient as $key => $patient)
                            <tr>
                                <th scope="row">{{ $loop->iteration }}</th>
                                <td> {{ $patient->name }} </td>
                                <td> {{ $patient->email }} </td>
                                <td> {{ $patient->tlp }} </td>
                                <td> {{ $patient->jeniskelamin }} </td>
                                <td>
                                    <a href="{{ route('patient.edit', ['patient' => $patient]) }}" class="btn btn-info"><i
                                            class="fa fa-pencil"></i> Edit </a>

                                    <form action="{{ route('patient.destroy', ['patient' => $patient]) }}"
                                        style="display: inline;" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger text-light">
                                            <i class="fa fa-trash" aria-hidden="true">
                                                Delete
                                            </i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $(function() {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });

    </script>
@endpush